/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.LoginControl;
import control.TillControl;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JButton;

/**
 *
 * @author Annette
 */
public class Frontpage extends javax.swing.JPanel {

    private final ScreenFormat sf;
    private final int screenWidth;
    private final int topGap;
    private final Dimension screenSize;
    private final LoginControl lc;
    private final TillControl tc;
    private final MainFrame mf;

    public Frontpage(LoginControl lc, TillControl tc, ScreenFormat sf, MainFrame mf) {
        initComponents();
        this.mf = mf;
        this.sf = sf;
        this.lc = lc;
        this.tc = tc;
        screenSize = sf.getScreenSize();
        topGap = sf.getTopGapSmall();
        screenWidth = sf.getScreenWidth();
        int buttonWidth = (int) (0.15 * screenWidth);
        int buttonHeight = (int) (0.04 * screenSize.height);
        setBounds(new Rectangle(screenSize));
        jLWelcome.setText("Velkommen " + lc.getEmployee().getFname());
        jLWelcome.setFont(sf.getFont());
        jLWelcome.setLocation((int) (0.7 * screenWidth), topGap);
        int welcomeLabelLength = (int) (screenSize.width * 0.30);
        jLWelcome.setSize(welcomeLabelLength, jLWelcome.getMinimumSize().height);
        jButtonSale.setFont(sf.getFont());
        jButtonTillReport.setFont(sf.getFont());
        jButtonStock.setFont(sf.getFont());
        jButtonStatistic.setFont(sf.getFont());
        jButtonLogout.setFont(sf.getFont());
        jButtonLogout.setSize(buttonWidth / 2, buttonHeight);
        jButtonLogout.setLocation((int) (0.9 * screenWidth), topGap);
        jButtonSale.setSize(buttonWidth, buttonHeight);
        jButtonTillReport.setSize(buttonWidth, buttonHeight);
        jButtonStock.setSize(buttonWidth, buttonHeight);
        jButtonStatistic.setSize(buttonWidth, buttonHeight);
        int buttonGap = (int) (0.175 * screenWidth);
        int buttonTopY = (int) (0.4 * screenSize.height);
        jButtonSale.setLocation(buttonGap, buttonTopY);
        jButtonStock.setLocation(buttonGap * 3 + buttonWidth, buttonTopY);
        int buttonBottomY = (int) (0.6 * screenSize.height);
        jButtonTillReport.setLocation(buttonGap, buttonBottomY);
        jButtonStatistic.setLocation(buttonGap * 3 + buttonWidth, buttonBottomY);
        int pictureX = screenWidth / 2 - jLabelPicture.getWidth() / 2;
        jLabelPicture.setLocation(pictureX, topGap);
        jLWelcome.setForeground(java.awt.Color.white);
        setComponentZOrder(jLWelcome, 3);
        setComponentZOrder(jLabelPicture, 4);
        setComponentZOrder(jButtonSale, 3);
        setComponentZOrder(jButtonStatistic, 3);
        setComponentZOrder(jButtonStock, 3);
        setComponentZOrder(jButtonTillReport, 3);
    }

    public JButton getButtonSale() {
        return jButtonSale;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSale = new javax.swing.JButton();
        jButtonTillReport = new javax.swing.JButton();
        jButtonStock = new javax.swing.JButton();
        jButtonStatistic = new javax.swing.JButton();
        jLabelPicture = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLWelcome = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);
        setLayout(null);

        jButtonSale.setText("Salg");
        jButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaleActionPerformed(evt);
            }
        });
        add(jButtonSale);
        jButtonSale.setBounds(238, 446, 109, 25);

        jButtonTillReport.setText("Kasserapport");
        jButtonTillReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillReportActionPerformed(evt);
            }
        });
        add(jButtonTillReport);
        jButtonTillReport.setBounds(238, 546, 109, 25);

        jButtonStock.setText("Varebeholdning");
        jButtonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockActionPerformed(evt);
            }
        });
        add(jButtonStock);
        jButtonStock.setBounds(510, 446, 110, 25);

        jButtonStatistic.setText("Statistik");
        jButtonStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatisticActionPerformed(evt);
            }
        });
        add(jButtonStatistic);
        jButtonStatistic.setBounds(510, 546, 109, 25);

        jLabelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/gasetarnet10.jpg"))); // NOI18N
        add(jLabelPicture);
        jLabelPicture.setBounds(120, 0, 600, 670);

        jButtonLogout.setText("Log ud");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        add(jButtonLogout);
        jButtonLogout.setBounds(791, 11, 67, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaleActionPerformed
        if (tc.getTill() == null) {
            try {
                if (!tc.openTill()) {
                    StartBalance startBalance = new StartBalance(mf, true);
                } else if (tc.getTill().isClosed()) {
                    jButtonSale.setEnabled(false);
                    new ErrorPopup("Kassen er lukket");
                } else {
                    if (!tc.getTill().isClosed()) {
                        mf.showCard("Salg");
                    } else {
                        jButtonSale.setEnabled(false);
                    }

                }
            } catch (Exception ex) {
                new ErrorPopup(ex.getMessage());
            }
        } else if (tc.getTill().isClosed()) {
            jButtonSale.setEnabled(false);
        } else {
            mf.showCard("Salg");
        }
    }//GEN-LAST:event_jButtonSaleActionPerformed

    private void jButtonStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatisticActionPerformed
        mf.showCard("Statistik");
    }//GEN-LAST:event_jButtonStatisticActionPerformed
    private void jButtonTillReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillReportActionPerformed
        mf.showCard("KasseRapport");
    }//GEN-LAST:event_jButtonTillReportActionPerformed

    private void jButtonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockActionPerformed
        mf.showCard("Varebeholdning");
    }//GEN-LAST:event_jButtonStockActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        mf.setVisible(false);
        LoginDialog loginDialog = new LoginDialog(lc, mf.getScreenFormat());
        mf.setVisible(true);
        jLWelcome.setText("Velkommen " + lc.getEmployee().getFname());
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSale;
    private javax.swing.JButton jButtonStatistic;
    private javax.swing.JButton jButtonStock;
    private javax.swing.JButton jButtonTillReport;
    private javax.swing.JLabel jLWelcome;
    private javax.swing.JLabel jLabelPicture;
    // End of variables declaration//GEN-END:variables
}
