/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ShopControl;
import java.util.ArrayList;
import model.Product;
import model.ProductGroup;

/**
 *
 * @author Hans
 */
public class Stock extends javax.swing.JPanel {

    private final MainFrame mf;
    private final ScreenFormat sf;

    /**
     * Creates new form Stock
     */
    public Stock(MainFrame mf) {
        initComponents();
        this.mf = mf;
        this.sf = mf.getScreenFormat();

        int smallTopGap = sf.getTopGapSmall();
        int defaultXGap = sf.getDefaultgap();
        int screenwidth = sf.getScreenWidth();

        jButtonHome.setLocation(defaultXGap, smallTopGap);
        jScrollPane1.setLocation(screenwidth / 2 - jScrollPane1.getWidth() / 2, smallTopGap);
        jButton1.setFont(sf.getFont());
        jButton2.setFont(sf.getFont());
        jButton1.setSize(sf.getButtonWidth(), sf.getDefaultButtonHeight());
        jButton2.setSize(sf.getButtonWidth(), sf.getDefaultButtonHeight());
        jButton1.setLocation(screenwidth - defaultXGap - jButton1.getWidth(), smallTopGap);
        jButton2.setLocation(jButton1.getX(), jButton1.getY() + jButton1.getHeight() + smallTopGap);

    }

    public void updateStock() {
        ShopControl sc = mf.getShopControl();
        ArrayList<ProductGroup> productGroupList = sc.getProductGroupList();
        for (ProductGroup productGroup : productGroupList) {
            ArrayList<Product> tempList = sc.getProductList(productGroup);
            for (Product product : tempList) {
                if (productGroup.getNr() != 1 && productGroup.getNr() != 4) {
                    jTextArea1.append(product.getName() + ": " + product.getAmount() + "\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(java.awt.Color.darkGray);
        setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 498, 791);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/home-icon.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        add(jButtonHome);
        jButtonHome.setBounds(739, 11, 50, 50);

        jButton1.setText("Tilføj ny vare");
        add(jButton1);
        jButton1.setBounds(730, 120, 97, 23);

        jButton2.setText("Genopfyld lager");
        add(jButton2);
        jButton2.setBounds(740, 170, 111, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        mf.showCard("Forside");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
